language: rust
cache: cargo
matrix:
  include:
    - rust: nightly
      env: RUN=BUILD
      before_script: rustup target add thumbv7m-none-eabi
      script: cargo build
    - rust: stable
      env: RUN=FMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
